### ISSUE TITLE
Bookmarklet: allow up to three images to be attached and removed

### ISSUE THREAD

**Issue by urbansheep** [FreeFeed/freefeed-react-client#263] opened 2016-02-09 16:09 UTC
In Friendfeed one could select up to three images to attach to the post created via the bookmarklet. We need to support that behavior in FreeFeed sharing bookmarklet.

- When user selects up to three images, their thumbnails are displayed in the image preview area of the sharing dialog.
- If user clicks on the thumbnail, it should disappear and this image should be removed from the posting queue.
- When fourth and subsequent images are clicked, they should be added as last image to the set, removing the first one from the queue.

**Comment by dsumin** [comment] 2016-02-09 16:23
And we could select feeds to post to (my feed, groups)

**Comment by urbansheep** [comment] 2016-02-09 16:24
@dsumin: Feed selection is a different issue: https://github.com/FreeFeed/freefeed-react-client/issues/200 )

**Comment by berkus** [comment] 2016-03-16 11:16
Dupe of https://dev.freefeed.net/T4

**Closed by berkus** 2016-03-16 11:16 UTC
