### ISSUE TITLE
Click on the comment cloud doesn't work if a text area for creating comment is already opened

### ISSUE THREAD

**Issue by govorkaya** [FreeFeed/freefeed-react-client#356] opened 2016-03-12 18:16 UTC
OS: Windows;
Browser: Chrome 49.0.2623.87

Steps: 
1. Navigate to a post with comments
2. Click on Add comment link 
3. Click on the comment cloud (to add @username into your comment) 

Actual result: 
Nothing happens.

Expected result: 
@username is added to the text of comment.

Additional information: 
If you navigate to the post and click on the comment cloud _without_ clicking «Comment» or «Add comment», it works perfectly. 
Moreover, if you reproduce steps 1-3, after that you click «Cancel», and then you click on the comment cloud (with text area for adding comment isn't shown on the screen) → you get a text area with doubled (!) «@username» in it.

**Comment by berkus** [comment] 2016-03-17 11:53
Dupe of https://dev.freefeed.net/T19

**Closed by berkus** 2016-03-17 11:53 UTC
