### ISSUE TITLE
Settings: Screen name fix — show character count and correct error message

### ISSUE THREAD

**Issue by urbansheep** [FreeFeed/freefeed-react-client#274] opened 2016-02-11 12:14 UTC
As of now we don't give feedback on allowed maximum length of the Screen Name. When said name is too long, we just respond with “Invalid screenname” message which doesn't help much.

Two proposed fixes are:
1) Error message for elaborate and excessively long screen names should read `Screen name is too long`.

2) Character count. Display a counter to the right side of the input field, with the explicit length of the current username and maximum limit. Mock up:
![frf-display-name-charcount](https://cloud.githubusercontent.com/assets/1756417/12975934/2eb24e42-d0d1-11e5-8fdd-2f5a5a6d155b.png)

**Comment by berkus** [comment] 2016-03-18 10:43
Dupe of https://dev.freefeed.net/T20

**Closed by berkus** 2016-03-18 10:43 UTC
