### ISSUE TITLE
likes/comments do not bring new posts via realtime

### ISSUE THREAD

**Issue by indeyets** [FreeFeed/freefeed-react-client#350] opened 2016-03-10 15:12 UTC
Realtime doesn't work correctly right now. 

* The page of any feed consists of N posts.
* We have various realtime-events which can happen. They include (at least):
 * New post
 * New like
 * New comment

The problem is, that "like" and "comment" events are ignored for the posts which are not present on the page right now. This cuts "friend-of-friend" posts-propagation and doesn't show posts with updated discussions.

Desired behavior is:

1. If new comment is delivered via realtime and it refers to the post which is not present on page, then post should be loaded via API and prepended to the page in a usual fashion
2. if new like is delivered via realtime and it refers to the post which is not present on page and it is a **first interaction** of You or Your friends with this post then it should be loaded via API and prepended to the page in a usual fashion

**first interaction** is deducted via comparing list of people to whom current user is subscribed and list of people who added likes/comments before current event

For sake of simplicity, we can ignore "first interaction" rule for now. Ember frontend doesn't adhere to it. In this case we should create separate issue about this

**Comment by kadmil** [comment] 2016-03-11 12:48
We add posts (via like and comment) should not be added to the first page, isn't it?

I could for now load data though api, but if it could be included in socket event — it would be way better. More than plain data loading, it could shift 'friend of a friend first interaction' to server, so frontend would not load all the post data to decide whether to add post to feed or not.

Speaking of comment section — I've got what needs to be done, but I think we need more specific decision of 'add to feed' logic for likes.

**Comment by berkus** [comment] 2016-03-16 11:27
Dupe of https://dev.freefeed.net/T6

**Closed by berkus** 2016-03-16 11:27 UTC
Labels: bug
