### ISSUE TITLE
Bookmarklet: support multiple destination feeds for a post

### ISSUE THREAD

**Issue by urbansheep** [FreeFeed/freefeed-react-client#200] opened 2016-01-25 07:22 UTC
At the moment the post created via bookmarklet is published to the main feed of the user only. Friendfeed allowed choosing any number of groups/users as a target, so that one post would be published to many recipients.

Our main interface allows that, but bookmarklet needs update to support that as well.

**Comment by berkus** [comment] 2016-03-16 11:15
Dupe of https://dev.freefeed.net/T3

**Closed by berkus** 2016-03-16 11:15 UTC
