### ISSUE TITLE
Best of day mailing list: "N more comments" link misaligned

### ISSUE THREAD

**Issue by dreikanter** [FreeFeed/freefeed-react-client#798] opened 2018-06-07 06:49 UTC
1. macOS, Chrome (latest, stable)
2. Best of day mailing list
3. Received and opened the email using gmail web client
4. Expected: The link should be alignment should be identical with Freefeed web UI
5. Actual: Link is shifted left

Here is the first post from the mailing list, for example:

![image](https://user-images.githubusercontent.com/126636/41082643-ac1be8aa-6a37-11e8-9b90-4a7afdc51e27.png)

Web version:

![image](https://user-images.githubusercontent.com/126636/41082732-f1f4f6dc-6a37-11e8-8aa9-f3a11ca7cf53.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/Z6p0Ecyb)

**Comment by dsumin** [comment] 2018-06-07 07:15
Duplicate of https://github.com/FreeFeed/freefeed-server/issues/335

**Closed as completed by dsumin** 2018-06-07 07:15 UTC
