### ISSUE TITLE
Add Google Analytics code 

### ISSUE THREAD

**Issue by payalnik** [FreeFeed/freefeed-react-client#351] opened 2016-03-11 01:52 UTC
1. Host https://github.com/googleanalytics/autotrack/blob/master/autotrack.js on Freefeed's servers 

2. Include this file with `<script async>` anywhere on the page

2. Add JS before `</body>`:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-62517081-1');
  ga('require', 'autotrack');
  ga('send', 'pageview');
</script>
```

This guy will automatically track all url changes.

**Comment by berkus** [comment] 2016-03-17 11:49
Dupe of https://dev.freefeed.net/T18

**Closed by berkus** 2016-03-17 11:49 UTC
