### ISSUE TITLE
[private groups] I can see my posts in private group after I have left this group

### ISSUE THREAD

**Issue by govorkaya** [FreeFeed/freefeed-react-client#343] opened 2016-03-09 16:05 UTC
>> Steps to reproduce:
1. Join any private group.
2. Write a post to this group.
3. Leave this group. 
4. (Go to another account that is also a member of this group and write a comment under the users1 post)

>> Actual result:
My post with a new comment appears in my home feed. 
I can't write a comment to this post; I can go to the separate page of this post but after renewal of the page I see only an error message  "can't find the post"

>> Expected result: 
I don't see any activity of the private group that I've left.

**Comment by dsumin** [comment] 2016-03-14 17:20
This won't be fixed until postgres.

**Comment by berkus** [comment] 2016-03-16 14:32
Dupe of https://dev.freefeed.net/T14

**Closed by berkus** 2016-03-16 14:32 UTC
