### ISSUE TITLE
Hover on username clears comment field

### ISSUE THREAD

**Issue by dandaka** [FreeFeed/freefeed-react-client#405] opened 2016-04-20 11:06 UTC
When reporting a bug please fill in the following:
1. Your OS name and vesion, browser name and version, is it mobile or desktop
   OSX, Chrome 50.0.2661.66 beta
2. Which version of freefeed were you using (ember frontend or old.freefeed.net, react frontend or freefeed.net, mobile version or m.freefeed.net, some other frontend)
   React freefeed.net
3. What did you do to trigger the bug
   — Click on the username bubble, to get username in comment field
   — Hover on username
   — Username disappears from comment field

https://www.dropbox.com/s/uwbygimnze83ihj/freefeed.mp4?dl=0
1. What result did you expect
   Hover doesn't change content in comment field.
2. What did actually happen
   Hover changes content in comment field.

**Comment by dsumin** [comment] 2016-04-20 11:09
Could you please try to reproduce this problem without betterfeed?

**Comment by dandaka** [comment] 2016-04-20 11:12
Can't reproduce. Maybe "turn off BetterFeed" should be here? Also there is a typo :) http://take.ms/UKIXa

**Comment by dandaka** [comment] 2016-04-20 11:12
@davidmz Should I report this bug to BetterFeed repo?

**Comment by berkus** [comment] 2016-04-20 11:17
Looks like BF bug, please report to them.

**Comment by davidmz** [comment] 2016-04-20 20:03
Thank you for report, yes, it is my bug. Fixed in BetterFeed 2.4.3.

**Closed as completed** 2016-04-21 04:48 UTC
