### ISSUE TITLE
I can choose a group that i just left as an addressee

### ISSUE THREAD

**Issue by govorkaya** [FreeFeed/freefeed-react-client#313] opened 2016-02-28 13:00 UTC
>> Steps:
1. Subscribe to the group
2. Unsubscribe
3. Go to home feed
4. Choose it in the list of potential addressee. 

>> Actual result:
You can choose this group, but you can't write a post in it. 
The group's title disappear only after refreshing of the page. 

>> Expected result:
I should not find the title of the group after I went to my home feed.

**Comment by berkus** [comment] 2016-03-17 09:25
Dupe of https://dev.freefeed.net/T17

**Closed by berkus** 2016-03-17 09:25 UTC
