### ISSUE TITLE
Private groups: subscription request

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#229] opened 2016-02-02 09:00 UTC
When navigating to a private group page or private group post page a user that is not a subscribers is shown the same "Request subscription" page that is displayed for private users.

Request subscription // link
sample-group has a private feed.

**Comment by berkus** [comment] 2016-03-16 12:37
Dupe of https://dev.freefeed.net/T10

**Closed by berkus** 2016-03-16 12:37 UTC
