### ISSUE TITLE
Realtime doesn't work after home page reloading

### ISSUE THREAD

**Issue by govorkaya** [FreeFeed/freefeed-react-client#331] opened 2016-03-04 10:21 UTC
(Chrome Version 48.0.2564.116 m on Windows)

Steps to reproduce: 
1. Open home page. Make sure realtime works.
2. Reload the page

Actual Result: 
Realtime doesn't work, you need to stop it and run it again. 

Expected result: 
Realtime keeps working.

**Comment by kadmil** [comment] 2016-03-10 14:36
I've done work around this, could you tell me whether this still reproduces or not?

**Comment by govorkaya** [comment] 2016-03-10 15:22
I can't reproduce it on george.freefeed.net

**Comment by kadmil** [comment] 2016-03-11 23:05
@berkus, @indeyets what should we do with seems-like-no-reproducible things like this?

**Comment by berkus** [comment] 2016-03-16 11:53
Dupe of https://dev.freefeed.net/T7

**Closed by berkus** 2016-03-16 11:53 UTC
