### ISSUE TITLE
Bookmarklet: alter size and position of a dialog to 7:5 ratio.

### ISSUE THREAD

**Issue by urbansheep** [FreeFeed/freefeed-react-client#325] opened 2016-03-02 12:31 UTC
As of now bookmarklet dialog is square 350 × 350 px and appears slightly to the left from the top right corner. I propose to:
- Remove right margin and
- Change the size of the bookmarklet dialog to a different proportion (520 × 370 px), to make it more comfortable for text entry and image thumbnails.

Below is a bookmarklet screenshot from the Friendfeed:
![image](https://cloud.githubusercontent.com/assets/1756417/13460440/96fdea6e-e08b-11e5-8c21-1ce6490e8c13.png)

**Comment by berkus** [comment] 2016-03-16 11:11
Dupe of https://dev.freefeed.net/T2

**Closed by berkus** 2016-03-16 11:11 UTC
