### ISSUE TITLE
Bookmarklet: display which feed the post will be posted to

### ISSUE THREAD

**Issue by urbansheep** [FreeFeed/freefeed-react-client#176] opened 2016-01-18 15:57 UTC
When posting a link via bookmarklet, sharing dialog doesn't specify the target feed (probably with assumption that if there's no way to change the destination then there's no need to show its name). Now multiple accounts are not so rare, so it would be great to have an explicit display of the destination feed to avoid misposts.

**Comment by berkus** [comment] 2016-03-16 11:18
Dupe of https://dev.freefeed.net/T5

**Closed by berkus** 2016-03-16 11:18 UTC
