### ISSUE TITLE
Private groups: group admins are shown pending subscription requests 

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#230] opened 2016-02-02 09:03 UTC
private groups admins are shown pending subscription requests in the home feed:
---
You have 1 subscription request(s) to review // Ссылка

[ small avatar ]
displayname (username) would like to subscribe to 'sample-group'
Accept request | Reject request

**Comment by berkus** [comment] 2016-03-16 12:39
Dupe of https://dev.freefeed.net/T11

**Closed by berkus** 2016-03-16 12:39 UTC
