### ISSUE TITLE
Realtime - comments appear without screen name

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-react-client#267] opened 2016-02-10 20:50 UTC
If a user has registered after the page was opened and starts commenting, the comments appear without screen name.

Console: 
`We've got comment with unknown author with id 6763be22-83f6-4742-8079-83b97550798e`

**Comment by kadmil** [comment] 2016-03-10 14:31
Must be fixed now, could you tell me, does this reproduce?

**Comment by berkus** [comment] 2016-03-16 11:56
Dupe of https://dev.freefeed.net/T8

**Closed by berkus** 2016-03-16 11:56 UTC
